# Generated by Django 4.1.1 on 2022-09-08 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='user_name')),
                ('password', models.CharField(max_length=256, verbose_name='password')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('correo', models.EmailField(max_length=100, verbose_name='correo')),
                ('direccion', models.CharField(max_length=100, verbose_name='direccion')),
                ('telefono', models.CharField(max_length=100, verbose_name='telefono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eps', models.CharField(max_length=15, verbose_name='eps')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('id_registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_registra_paciente', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_paciente', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('saturacion', models.IntegerField(verbose_name='saturacion')),
                ('presion', models.IntegerField(verbose_name='presion')),
                ('frecuencia_cardiaca', models.IntegerField(verbose_name='frecuencia_cardiaca')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('id_familiar_registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_familiar_registra', to='hospital_casa_app.paciente')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente', to='hospital_casa_app.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profesion', models.CharField(max_length=15, verbose_name='profesion')),
                ('nivel', models.IntegerField(default=0, verbose_name='nivel')),
                ('especialidad', models.CharField(max_length=15, verbose_name='especialidad')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('id_registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_registra_medico', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_medico', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('id_registra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_registra_familiar', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_usuario_familiar', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
