# Generated by Django 4.1.1 on 2022-09-09 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_casa_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='signosvitales',
            name='id_familiar_registra',
        ),
        migrations.RemoveField(
            model_name='signosvitales',
            name='id_paciente',
        ),
        migrations.AddField(
            model_name='familiar',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_familiar', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_medico', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_paciente', to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='id_registra',
            field=models.IntegerField(blank=True, null=True, verbose_name='id_registra'),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente', to='hospital_casa_app.paciente'),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='id_registra',
            field=models.IntegerField(blank=True, null=True, verbose_name='id_registra'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id_registra',
            field=models.IntegerField(blank=True, null=True, verbose_name='id_registra'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_registra',
            field=models.IntegerField(blank=True, null=True, verbose_name='id_registra'),
        ),
    ]
