# Generated by Django 4.1.1 on 2022-09-15 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_casa_app', '0004_alter_paciente_create_date_alter_user_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('MEDICO', 'Med'), ('ENFERMER@', 'Enf'), ('PACIENTE', 'Pac'), ('FAMILIAR', 'Fam'), ('AUXILIAR', 'Aux')], default='PACIENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=20, verbose_name='cargo')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('id_registra', models.IntegerField(blank=True, null=True, verbose_name='id_registra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_auxiliar', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
