# Generated by Django 4.1.1 on 2022-09-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_casa_app', '0005_rename_id_usuario_paciente_usuario_user_rol_auxiliar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliar',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='cargo'),
        ),
    ]
